package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_scala//scala:scala.bzl", "scala_binary", "scala_library", "scala_test")

scala_library(
    name = "intl_formatter",
    srcs = glob(["*.scala"]),
    deps = [
        "@org_graalvm_sdk_2_0_0_2",
    ]
)
